import { act, fireEvent, render, screen } from '@testing-library/react';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { apiDemoExamples } from '@/data/api-demo';
import { ApiRequestPlayer, type ApiRequestPlayerLabels } from './api-request-player';

const labels: ApiRequestPlayerLabels = {
  run: 'Run',
  running: 'Running…',
  pending: 'Pending…',
  streaming: 'Streaming…',
  copy: 'Copy',
  copied: 'Copied!',
  done: 'Response received',
  responsePlaceholder: 'The response will appear here — press Run',
  previewTab: 'Preview',
  responseTab: 'Response',
  previewIdle: 'The preview will appear here once the response completes',
  previewAlt: 'Preview generated by the sample endpoint',
  fullscreen: 'Fullscreen',
  endpoint: 'Endpoint',
  examples: {
    image: 'Image',
    video: 'Video',
    audio: 'Audio',
    error: 'Error',
  },
  previewError: 'The request failed',
  audio: { play: 'Play track', pause: 'Pause track' },
  lightbox: {
    controls: 'Controls',
    zoomIn: 'Zoom in',
    zoomOut: 'Zoom out',
    zoomLevel: 'Zoom {percent}%',
    reset: 'Reset view',
    fit: 'Fit: {current}. Switch to {next}',
    fullscreen: 'Enter fullscreen',
    exitFullscreen: 'Exit fullscreen',
    hideControls: 'Hide controls',
    showControls: 'Show controls',
    close: 'Close',
    help: 'Keyboard shortcuts',
    helpTitle: 'Keyboard shortcuts',
    shortcutZoom: 'Zoom in / out',
    shortcutReset: 'Reset view',
    shortcutPanKeys: 'Pan',
    shortcutPanDrag: 'Hold Space and drag to pan',
    shortcutFit: 'Cycle fit mode (toolbar)',
    shortcutFullscreen: 'Toggle fullscreen',
    shortcutControls: 'Show / hide controls',
    shortcutHelp: 'Toggle this help',
    shortcutClose: 'Close',
  },
};

const REDUCED_MOTION_QUERY = '(prefers-reduced-motion: reduce)';

function stubReducedMotion(matches: boolean) {
  Object.defineProperty(window, 'matchMedia', {
    writable: true,
    configurable: true,
    value: vi.fn().mockImplementation((query: string) => ({
      matches: query === REDUCED_MOTION_QUERY ? matches : false,
      media: query,
      onchange: null,
      addListener: vi.fn(),
      removeListener: vi.fn(),
      addEventListener: vi.fn(),
      removeEventListener: vi.fn(),
      dispatchEvent: vi.fn(),
    })),
  });
}

function renderPlayer() {
  return render(<ApiRequestPlayer examples={apiDemoExamples} labels={labels} />);
}

/**
 * Deterministic rAF stub (same pattern as tilt-card/animated-metric): jsdom
 * does not include a synchronous scheduler, so without this, player streaming never
 * advances in tests. Local to each test via `vi.stubGlobal` + `afterEach(vi.unstubAllGlobals)`.
 */
function stubAnimationFrame() {
  let nextId = 0;
  const frames = new Map<number, FrameRequestCallback>();
  vi.stubGlobal('requestAnimationFrame', (cb: FrameRequestCallback): number => {
    const id = ++nextId;
    frames.set(id, cb);
    return id;
  });
  vi.stubGlobal('cancelAnimationFrame', (id: number) => {
    frames.delete(id);
  });
  return {
    /** Ejecuta los frames agendados en este instante (una "ronda" de streaming). */
    flush: () => {
      const pending = Array.from(frames.values());
      frames.clear();
      act(() => {
        for (const cb of pending) cb(0);
      });
    },
    /** Runs rounds until no scheduled frames remain (streaming complete). */
    flushAll: () => {
      let guard = 0;
      while (frames.size > 0 && guard < 1000) {
        const pending = Array.from(frames.values());
        frames.clear();
        act(() => {
          for (const cb of pending) cb(0);
        });
        guard += 1;
      }
    },
    pendingCount: () => frames.size,
  };
}

describe('ApiRequestPlayer', () => {
  afterEach(() => {
    vi.unstubAllGlobals();
    vi.useRealTimers();
  });

  it('idle shows the request and the run button', () => {
    renderPlayer();
    expect(screen.getByText(/text-to-image/)).toBeInTheDocument();
    expect(screen.getByRole('button', { name: labels.run })).toBeInTheDocument();
  });

  it('idle shows a placeholder in the response instead of an empty <pre>', () => {
    renderPlayer();
    expect(screen.getByText(labels.responsePlaceholder)).toBeInTheDocument();
  });

  it('during pending, a status label in font-mono accompanies the spinner', () => {
    vi.useFakeTimers({ toFake: ['setTimeout', 'clearTimeout'] });
    stubReducedMotion(true);
    renderPlayer();
    fireEvent.click(screen.getByRole('button', { name: labels.run }));
    expect(screen.getByText(labels.pending)).toBeInTheDocument();
  });

  it('during streaming, a status label in font-mono accompanies the caret', () => {
    vi.useFakeTimers({ toFake: ['setTimeout', 'clearTimeout'] });
    const frame = stubAnimationFrame();
    stubReducedMotion(false);
    renderPlayer();

    fireEvent.click(screen.getByRole('button', { name: labels.run }));
    act(() => vi.advanceTimersByTime(600));
    frame.flush();

    expect(screen.getByText(labels.streaming)).toBeInTheDocument();
    expect(screen.getByText('▌')).toBeInTheDocument();

    frame.flushAll();
  });

  it('run → pending → done con la respuesta completa (reduced-motion: sin typing)', async () => {
    stubReducedMotion(true);
    renderPlayer();
    fireEvent.click(screen.getByRole('button', { name: labels.run }));
    expect(await screen.findByText(/COMPLETED/)).toBeInTheDocument();
    expect(screen.getByText('200 OK')).toBeInTheDocument();
  });

  it('the copy button copies the response', async () => {
    const writeText = vi.fn().mockResolvedValue(undefined);
    vi.stubGlobal('navigator', { ...navigator, clipboard: { writeText } });
    stubReducedMotion(true);
    renderPlayer();
    fireEvent.click(screen.getByRole('button', { name: labels.run }));
    await screen.findByText(/COMPLETED/);
    fireEvent.click(screen.getByRole('button', { name: labels.copy }));
    expect(writeText).toHaveBeenCalled();
  });

  it('during pending, the run button is disabled and shows the "running" label', () => {
    vi.useFakeTimers({ toFake: ['setTimeout', 'clearTimeout'] });
    stubReducedMotion(true);
    renderPlayer();
    fireEvent.click(screen.getByRole('button', { name: labels.run }));
    expect(screen.getByRole('button', { name: labels.running })).toBeDisabled();
  });

  it('sin reduced-motion, la respuesta se escribe en streaming con caret y termina en done', () => {
    vi.useFakeTimers({ toFake: ['setTimeout', 'clearTimeout'] });
    const frame = stubAnimationFrame();
    stubReducedMotion(false);
    renderPlayer();

    fireEvent.click(screen.getByRole('button', { name: labels.run }));
    act(() => vi.advanceTimersByTime(600));

    const fullResponse = JSON.stringify(apiDemoExamples[0]?.response, null, 2);
    frame.flush();
    expect(screen.queryByText(fullResponse)).not.toBeInTheDocument();
    expect(screen.getByText('▌')).toBeInTheDocument();

    frame.flushAll();
    expect(screen.getByText(/COMPLETED/)).toBeInTheDocument();
    expect(screen.queryByText('▌')).not.toBeInTheDocument();
    expect(screen.getByRole('button', { name: labels.run })).toBeInTheDocument();
  });

  it('reejecutable: correr de nuevo desde done resetea y vuelve a completar la respuesta', async () => {
    stubReducedMotion(true);
    renderPlayer();
    fireEvent.click(screen.getByRole('button', { name: labels.run }));
    await screen.findByText(/COMPLETED/);

    fireEvent.click(screen.getByRole('button', { name: labels.run }));
    expect(screen.getByRole('button', { name: labels.running })).toBeInTheDocument();

    await screen.findByText(/COMPLETED/);
    expect(screen.getByText('200 OK')).toBeInTheDocument();
  });

  it('copy sin clipboard disponible no rompe', async () => {
    vi.stubGlobal('navigator', { ...navigator, clipboard: undefined });
    stubReducedMotion(true);
    renderPlayer();
    fireEvent.click(screen.getByRole('button', { name: labels.run }));
    await screen.findByText(/COMPLETED/);
    expect(() => fireEvent.click(screen.getByRole('button', { name: labels.copy }))).not.toThrow();
  });

  it('desmontar durante pending cancela el timeout pendiente (mecanismo, no solo ausencia de crash)', () => {
    // React 19 vuelve un no-op silencioso el setState post-unmount (ya no hay warning
    // "state update on an unmounted component"), so "does not throw / does not do
    // console.error" NO discrimina si el cleanup deja de llamar clearTimeout. La
    // actual assertion is on the fake timers engine: `getTimerCount()` counts
    // timers (`setTimeout`) still pending — must go from 1 to 0 on unmount.
    vi.useFakeTimers({ toFake: ['setTimeout', 'clearTimeout'] });
    stubReducedMotion(true);
    const { unmount } = renderPlayer();

    fireEvent.click(screen.getByRole('button', { name: labels.run }));
    expect(screen.getByRole('button', { name: labels.running })).toBeInTheDocument();
    expect(vi.getTimerCount()).toBe(1);

    // Desmonta ANTES de que el setTimeout de 600ms llegue a disparar.
    unmount();
    expect(vi.getTimerCount()).toBe(0);
  });

  it('si el portapapeles rechaza, no crashea, no deja unhandled rejection y no queda "copied"', async () => {
    const writeText = vi.fn().mockRejectedValue(new Error('denied'));
    vi.stubGlobal('navigator', { ...navigator, clipboard: { writeText } });
    const consoleError = vi.spyOn(console, 'error').mockImplementation(() => {});
    stubReducedMotion(true);
    renderPlayer();

    fireEvent.click(screen.getByRole('button', { name: labels.run }));
    await screen.findByText(/COMPLETED/);

    await act(async () => {
      fireEvent.click(screen.getByRole('button', { name: labels.copy }));
      // Deja correr el microtask del catch antes de aserciones (evita el warning
      // "not wrapped in act" por el setState que NO llega a producirse).
      await Promise.resolve();
    });

    expect(writeText).toHaveBeenCalled();
    expect(screen.getByRole('button', { name: labels.copy })).toBeInTheDocument();
    expect(screen.queryByText(labels.copied)).not.toBeInTheDocument();
    expect(consoleError).not.toHaveBeenCalled();
    consoleError.mockRestore();
  });

  it('unmounting during streaming cleans up timeout and rAF without leaving an orphaned setState', () => {
    vi.useFakeTimers({ toFake: ['setTimeout', 'clearTimeout'] });
    const frame = stubAnimationFrame();
    const consoleError = vi.spyOn(console, 'error').mockImplementation(() => {});
    stubReducedMotion(false);
    const { unmount } = renderPlayer();

    fireEvent.click(screen.getByRole('button', { name: labels.run }));
    act(() => vi.advanceTimersByTime(600));
    frame.flush();
    expect(frame.pendingCount()).toBe(1);

    unmount();
    expect(frame.pendingCount()).toBe(0);
    expect(() => act(() => vi.advanceTimersByTime(600))).not.toThrow();
    expect(consoleError).not.toHaveBeenCalled();
    consoleError.mockRestore();
  });

  it('anuncia la respuesta recibida solo al llegar a done, en un contenedor sr-only role=status', async () => {
    stubReducedMotion(true);
    renderPlayer();
    expect(screen.getByRole('status')).toHaveTextContent('');

    fireEvent.click(screen.getByRole('button', { name: labels.run }));
    await screen.findByText(/COMPLETED/);
    expect(screen.getByRole('status')).toHaveTextContent(labels.done);
  });

  it('the status row is also reserved in idle (zero shift)', () => {
    renderPlayer();
    expect(screen.getByTestId('player-status-row')).toHaveClass('min-h-8');
  });

  it('la respuesta escribe dentro de un panel de altura fija', async () => {
    renderPlayer();
    const pane = screen.getByTestId('player-response-pane');
    expect(pane).toHaveClass('h-64');
    fireEvent.click(screen.getByRole('button', { name: labels.run }));
    await screen.findByText(labels.done, {}, { timeout: 3000 });
    expect(pane).toHaveClass('h-64'); // no class change/reserved size
  });

  it('done muestra la preview con fullscreen', async () => {
    renderPlayer();
    fireEvent.click(screen.getByRole('button', { name: labels.run }));
    await screen.findByText(labels.done, {}, { timeout: 3000 });
    fireEvent.click(screen.getByRole('tab', { name: labels.previewTab }));
    expect(screen.getByRole('img', { name: labels.previewAlt })).toBeInTheDocument();
    fireEvent.click(screen.getByRole('button', { name: labels.fullscreen }));
    expect(screen.getByRole('dialog')).toBeInTheDocument();
  });

  it('the selector changes method/path/body and resets the player to idle', async () => {
    stubReducedMotion(true);
    renderPlayer();
    fireEvent.click(screen.getByRole('button', { name: labels.run }));
    await screen.findByText(labels.done);

    const endpointSelect = screen.getByRole('combobox', { name: labels.endpoint });
    expect(endpointSelect).toHaveClass('transition-colors', 'hover:border-fg-muted');
    // flex-1 gobierna el ancho: el w-full por defecto del Select queda muerto y no debe llegar al DOM.
    expect(endpointSelect).toHaveClass('flex-1');
    expect(endpointSelect).not.toHaveClass('w-full');
    fireEvent.change(endpointSelect, {
      target: { value: 'error' },
    });

    expect(screen.getByText('/v1/ai/text-to-image')).toBeInTheDocument();
    expect(screen.getByText(/ultra_wide_32_9/)).toBeInTheDocument();
    expect(screen.getByText(labels.responsePlaceholder)).toBeInTheDocument();
  });

  it('el ejemplo de error termina en 400 con el JSON de error en Response', async () => {
    stubReducedMotion(true);
    renderPlayer();
    fireEvent.change(screen.getByRole('combobox', { name: labels.endpoint }), {
      target: { value: 'error' },
    });
    fireEvent.click(screen.getByRole('button', { name: labels.run }));

    expect(await screen.findByText('400 Bad Request')).toHaveClass('bg-danger/15', 'text-danger');
    expect(screen.getByTestId('player-response-pane').textContent).toContain('validation_error');
  });

  it('a 5xx status also renders the danger badge (not only 4xx)', async () => {
    stubReducedMotion(true);
    const withServerError = apiDemoExamples.map((entry) =>
      entry.id === 'error' ? { ...entry, status: '500 Internal Server Error' } : entry,
    );
    render(<ApiRequestPlayer examples={withServerError} labels={labels} />);
    fireEvent.change(screen.getByRole('combobox', { name: labels.endpoint }), {
      target: { value: 'error' },
    });
    fireEvent.click(screen.getByRole('button', { name: labels.run }));

    expect(await screen.findByText('500 Internal Server Error')).toHaveClass(
      'bg-danger/15',
      'text-danger',
    );
  });

  it('conserva las cajas de altura fija al cambiar de endpoint', () => {
    renderPlayer();
    const requestPane = screen.getByTestId('player-request-pane');
    expect(requestPane).toHaveClass('h-40');

    fireEvent.change(screen.getByRole('combobox', { name: labels.endpoint }), {
      target: { value: 'video' },
    });

    expect(screen.getByTestId('player-request-pane')).toHaveClass('h-40');
    expect(screen.getByTestId('player-status-row')).toBeInTheDocument();
  });

  it('the video preview mounts video with poster and controls only after done', async () => {
    stubReducedMotion(true);
    renderPlayer();
    fireEvent.change(screen.getByRole('combobox', { name: labels.endpoint }), {
      target: { value: 'video' },
    });
    expect(document.querySelector('video')).toBeNull();

    fireEvent.click(screen.getByRole('button', { name: labels.run }));
    await screen.findByText(labels.done);
    fireEvent.click(screen.getByRole('tab', { name: labels.previewTab }));

    const video = document.querySelector('video');
    expect(video).toHaveAttribute('poster');
    expect(video).toHaveAttribute('controls');
  });

  it('the audio preview shows cover and compact controls', async () => {
    stubReducedMotion(true);
    renderPlayer();
    fireEvent.change(screen.getByRole('combobox', { name: labels.endpoint }), {
      target: { value: 'audio' },
    });
    fireEvent.click(screen.getByRole('button', { name: labels.run }));
    await screen.findByText(labels.done);
    fireEvent.click(screen.getByRole('tab', { name: labels.previewTab }));

    expect(screen.getByRole('img', { name: labels.previewAlt })).toBeInTheDocument();
    expect(screen.getByRole('button', { name: labels.audio.play })).toBeInTheDocument();
  });

  it('the error preview shows the designed state without fullscreen', async () => {
    stubReducedMotion(true);
    renderPlayer();
    fireEvent.change(screen.getByRole('combobox', { name: labels.endpoint }), {
      target: { value: 'error' },
    });
    fireEvent.click(screen.getByRole('button', { name: labels.run }));
    await screen.findByText(labels.done);
    fireEvent.click(screen.getByRole('tab', { name: labels.previewTab }));

    expect(screen.getByText(labels.previewError)).toBeInTheDocument();
    expect(screen.queryByRole('button', { name: labels.fullscreen })).not.toBeInTheDocument();
  });

  it('the image preview uses explicit width and height', async () => {
    stubReducedMotion(true);
    renderPlayer();
    fireEvent.click(screen.getByRole('button', { name: labels.run }));
    await screen.findByText(labels.done);
    fireEvent.click(screen.getByRole('tab', { name: labels.previewTab }));

    const preview = apiDemoExamples[0]?.preview;
    if (!preview || preview.kind !== 'image') throw new Error('Fixture image ausente');
    expect(screen.getByRole('img', { name: labels.previewAlt })).toHaveAttribute(
      'width',
      String(preview.width),
    );
    expect(screen.getByRole('img', { name: labels.previewAlt })).toHaveAttribute(
      'height',
      String(preview.height),
    );
  });
});
